services:
  - type: web
    name: sira-web
    runtime: static
    buildCommand: "bash scripts/render_build.sh"
    staticPublishPath: build/web
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: ASR_SPACE_URL
        value: https://binaryMao-sira-asr.hf.space/transcribe
      - key: DJELIA_API_KEY
        sync: false
