name: Deploy to GitHub Pages
on:
  push:
    branches: [ deploy-v2, main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build web --release --no-tree-shake-icons
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: build/web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}